[package]
name = "aws_imagebuilder_component"
version = "0.1.0"
edition = "2021"

[dependencies]
either = { version = "1", features = ["serde"]}
serde ={ version = "1", features = ["derive"] }

[dev-dependencies]
serde_yaml = "0.9.34"
